{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d43a499f_ce5f2652",
        "filename": "gsutil.py",
        "patchSetId": 14
      },
      "lineNbr": 213,
      "author": {
        "id": 1116069
      },
      "writtenOn": "2023-01-13T16:31:03Z",
      "side": 1,
      "message": "This \u0027encoding\u0027 argument requires python version 3.10.\nIs this a minimum requirement for depot_tools now?\nWe are running this utility on python version 3.5, and it is now failing.",
      "range": {
        "startLine": 213,
        "startChar": 31,
        "endLine": 213,
        "endChar": 53
      },
      "revId": "5e5802d7a244d01039076113b3d91b953105c58b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6ef95b4c_e6519fe2",
        "filename": "gsutil.py",
        "patchSetId": 14
      },
      "lineNbr": 213,
      "author": {
        "id": 1529602
      },
      "writtenOn": "2023-01-13T16:43:10Z",
      "side": 1,
      "message": "I have approved the revert for now for fix the immediate issue.\n\n\u003e We are running this utility on python version 3.5\n\ndepot_tools requires python 3.8[1]. Is there a reason the utility still uses 3.5? On that note, `subprocess.run` is not a part of py 2.7 anyway so this needs a fix.\n\n[1] https://chromium.googlesource.com/chromium/tools/depot_tools/+/HEAD/README.md",
      "parentUuid": "d43a499f_ce5f2652",
      "range": {
        "startLine": 213,
        "startChar": 31,
        "endLine": 213,
        "endChar": 53
      },
      "revId": "5e5802d7a244d01039076113b3d91b953105c58b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "93357be8_16045223",
        "filename": "gsutil.py",
        "patchSetId": 14
      },
      "lineNbr": 213,
      "author": {
        "id": 1529602
      },
      "writtenOn": "2023-01-13T16:48:32Z",
      "side": 1,
      "message": "\u003e This \u0027encoding\u0027 argument requires python version 3.10.\n\nThe argument is a part of py3.6[1].\n\n[1] https://docs.python.org/3.6/library/subprocess.html#subprocess.run",
      "parentUuid": "6ef95b4c_e6519fe2",
      "range": {
        "startLine": 213,
        "startChar": 31,
        "endLine": 213,
        "endChar": 53
      },
      "revId": "5e5802d7a244d01039076113b3d91b953105c58b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "84d5a8ab_3a2f6d5b",
        "filename": "gsutil.py",
        "patchSetId": 14
      },
      "lineNbr": 213,
      "author": {
        "id": 1529602
      },
      "writtenOn": "2023-01-13T17:00:25Z",
      "side": 1,
      "message": "```\n#!/usr/bin/env python3\n```\n\nLooking into this, `gsutil.py` is set to run with py3 as default and the minimum requirement for py3 is 3.8, which supports this argument. Is there a reason for your utility to run in 3.5?",
      "parentUuid": "93357be8_16045223",
      "range": {
        "startLine": 213,
        "startChar": 31,
        "endLine": 213,
        "endChar": 53
      },
      "revId": "5e5802d7a244d01039076113b3d91b953105c58b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "1e13a4a2_4932eb54",
        "filename": "gsutil.py",
        "patchSetId": 14
      },
      "lineNbr": 213,
      "author": {
        "id": 1116069
      },
      "writtenOn": "2023-01-13T17:02:32Z",
      "side": 1,
      "message": "Our server is running on Google Cloud VM image from Ubuntu 16.04. We have had an issue filed to update it, so we will update it to 18 or 20 now.  Our workaround is just to use an earlier version of depot_tools right now, but we can update the server next week, since the Python requirement is 3.8.\n\nI see that the reference I found was for a different call, not subprocess, so yes, the reverted CL only requires 3.6, and should be accepted in depot_tools. We do have a workaround, but we will also no longer need the workaround next week, so waiting until then to reland would be helpful.",
      "parentUuid": "6ef95b4c_e6519fe2",
      "range": {
        "startLine": 213,
        "startChar": 31,
        "endLine": 213,
        "endChar": 53
      },
      "revId": "5e5802d7a244d01039076113b3d91b953105c58b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}