{
  "comments": [
    {
      "key": {
        "uuid": "c39df4b9_3248384f",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T17:50:16Z",
      "side": 1,
      "message": "hm, are you sure this won\u0027t break bots?\nYour led task failed in bot_update step https://ci.chromium.org/swarming/task/3d5d04c95a1e4f10?server\u003dchromium-swarm.appspot.com with cryptic (to me) error.",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "056c573d_039100fc",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2018-05-09T21:17:41Z",
      "side": 1,
      "message": "Actually, I was not able to find the way to only apply this CL by led.\n\nBut I think this change is safe.\nThe led task was run by setting GIT_TRACE\u003d1 globally in bot_update step, and the failure is happened in L730 in this diff.\nThat is due to value containing output from GIT_TRACE in |mirror_dir| (L717) and it was passed to git in L730.\n\nSo the error happened after populate_cmd, and we don\u0027t use output of populate_cmd. I think this is safe to land.",
      "parentUuid": "c39df4b9_3248384f",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "7502e6c1_e6d91df9",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T21:35:35Z",
      "side": 1,
      "message": "\u003e Actually, I was not able to find the way to only apply this CL by led.\n\ncan you elaborate?\n\n\u003e The led task was run by setting GIT_TRACE\u003d1 globally in bot_update step\nAh, I see what you mean now. OK, looks safe to me too. However, you\u0027d make me happier if you trigger this latest patch with LED.",
      "parentUuid": "056c573d_039100fc",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6ec9855d_f0c2fac5",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2018-05-09T21:50:58Z",
      "side": 1,
      "message": "\u003e \u003e Actually, I was not able to find the way to only apply this CL by led.\n\u003e \n\u003e can you elaborate?\n\u003e \n\nTo apply this patch, in my understanding, I need to simulate following by LED.\n* roll this CL\n* update DEPS in chromium/src for bot_update\n* GIT_TRACE has affect in bot_update step on the bots who already run bot_update step syncing DEPS for bot_update module in previous build\n\nBut couldn\u0027t come up the way to do.\n\nOr do I miss something?\nHow do you do test by LED when modifying bot_update module?",
      "parentUuid": "7502e6c1_e6d91df9",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d7f95e8d_1e762abf",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T22:03:24Z",
      "side": 1,
      "message": "ah, it\u0027s easy -- you\u0027ve missed -O flag for that!\n\n$ cd build/scripts/slaves/recipes\n$ led get-builder \u003cid\u003e | led edit-recipe-bundle -O depot_tools\u003d/path/to/depot_tools/with/your/patch | led launch",
      "parentUuid": "6ec9855d_f0c2fac5",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c0bfaec5_da6d7670",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2018-05-09T22:18:01Z",
      "side": 1,
      "message": "Thank you!\nAnd I found a bug, fixed.",
      "parentUuid": "d7f95e8d_1e762abf",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6f461af5_454d3d72",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 679,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T17:50:16Z",
      "side": 1,
      "message": "nit: del 1 empty line",
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a69d066b_9057884a",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 679,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2018-05-09T21:17:41Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "6f461af5_454d3d72",
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}