{
  "comments": [
    {
      "key": {
        "uuid": "26f280af_321ddd70",
        "filename": "git_cl.py",
        "patchSetId": 7
      },
      "lineNbr": 1388,
      "author": {
        "id": 1367760
      },
      "writtenOn": "2020-02-05T23:24:13Z",
      "side": 1,
      "message": "how confident are you that this is never called with a description, but without an issue?\nShould UpdateDescription have a similar assert?",
      "range": {
        "startLine": 1388,
        "startChar": 0,
        "endLine": 1388,
        "endChar": 63
      },
      "revId": "be3538cfa5464d01218b7b83f75a50a41ec62499",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}