{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c57cdd02_2a6a57c5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1367998
      },
      "writtenOn": "2021-05-13T01:38:31Z",
      "side": 1,
      "message": "led run with change: https://luci-milo.appspot.com/raw/build/logs.chromium.org/chromium/led/gavinmak_google.com/73a0bcb2cb4aa4e50de6770117037f71c5be5858232c8340fa4c6118cf5ab7ab/+/annotations\n\nwithout: https://ci.chromium.org/ui/p/chromium/builders/try/win_chromium_compile_dbg_ng/865694/overview",
      "revId": "d2178db23c18af255c518790fea8c3b383a59100",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "8b4bc0ec_6f2e83e0",
        "filename": "recipes/recipe_modules/bot_update/api.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 1167909
      },
      "writtenOn": "2021-05-13T16:29:27Z",
      "side": 1,
      "message": "How does it look if we move from the comment below to here?",
      "revId": "d2178db23c18af255c518790fea8c3b383a59100",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "54d1b85a_fe2b8e44",
        "filename": "recipes/recipe_modules/bot_update/api.py",
        "patchSetId": 1
      },
      "lineNbr": 334,
      "author": {
        "id": 1367998
      },
      "writtenOn": "2021-05-13T19:00:25Z",
      "side": 1,
      "message": "https://ci.chromium.org/raw/build/logs.chromium.org/chromium/led/gavinmak_google.com/b89588d119c4c7529d0ddd44727afc46ab8dc9f754c2719f9713dbec3b782bc9/+/annotations?server\u003dchromium-swarm.appspot.com\n\nEssentially the same thing as before, but the patch error log moves to bot_update. I wonder if it\u0027s fine to delete the extra \u0027TRYJOB FAILURE\u0027 and \u0027Patch failure\u0027 steps with this change?",
      "parentUuid": "8b4bc0ec_6f2e83e0",
      "revId": "d2178db23c18af255c518790fea8c3b383a59100",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9eb5b25a_2fc835b5",
        "filename": "recipes/recipe_modules/bot_update/api.py",
        "patchSetId": 1
      },
      "lineNbr": 417,
      "author": {
        "id": 1167909
      },
      "writtenOn": "2021-05-13T16:29:27Z",
      "side": 1,
      "message": "How does it look if we move this above?\n\n  if result.get(\u0027failed_patch_body\u0027):\n    step_result.presentation.logs[\u0027patch error\u0027] \u003d (\n        result[\u0027failed_patch_body\u0027].splitlines())\n\nWill the link to the patch error be shown in Gerrit?",
      "range": {
        "startLine": 414,
        "startChar": 0,
        "endLine": 417,
        "endChar": 0
      },
      "revId": "d2178db23c18af255c518790fea8c3b383a59100",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "50a4258b_7a604822",
        "filename": "recipes/recipe_modules/bot_update/api.py",
        "patchSetId": 1
      },
      "lineNbr": 417,
      "author": {
        "id": 1367998
      },
      "writtenOn": "2021-05-13T19:00:25Z",
      "side": 1,
      "message": "Yes, if Checks is enabled. Checks links to logs of the first failed step",
      "parentUuid": "9eb5b25a_2fc835b5",
      "range": {
        "startLine": 414,
        "startChar": 0,
        "endLine": 417,
        "endChar": 0
      },
      "revId": "d2178db23c18af255c518790fea8c3b383a59100",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}